// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8CQErlhUgXn-o8LXzQ1cQzVjcMJXqjX8',
    appId: '1:559207605989:web:d11af842b693c1aa91160c',
    messagingSenderId: '559207605989',
    projectId: 'fir-test-project-2026',
    authDomain: 'fir-test-project-2026.firebaseapp.com',
    storageBucket: 'fir-test-project-2026.firebasestorage.app',
    measurementId: 'G-65G2JW9T5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLt0aT_-jSdUSkn6ikg9kNx0Ues7gfkBE',
    appId: '1:559207605989:android:ad72ac32c11f65bd91160c',
    messagingSenderId: '559207605989',
    projectId: 'fir-test-project-2026',
    storageBucket: 'fir-test-project-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLWA3pQIelcauM1MsC8cgCIxbjbwaGS8Y',
    appId: '1:559207605989:ios:ebae98a30414347e91160c',
    messagingSenderId: '559207605989',
    projectId: 'fir-test-project-2026',
    storageBucket: 'fir-test-project-2026.firebasestorage.app',
    iosBundleId: 'com.example.fbTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLWA3pQIelcauM1MsC8cgCIxbjbwaGS8Y',
    appId: '1:559207605989:ios:ebae98a30414347e91160c',
    messagingSenderId: '559207605989',
    projectId: 'fir-test-project-2026',
    storageBucket: 'fir-test-project-2026.firebasestorage.app',
    iosBundleId: 'com.example.fbTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8CQErlhUgXn-o8LXzQ1cQzVjcMJXqjX8',
    appId: '1:559207605989:web:82de5d8c46ade31591160c',
    messagingSenderId: '559207605989',
    projectId: 'fir-test-project-2026',
    authDomain: 'fir-test-project-2026.firebaseapp.com',
    storageBucket: 'fir-test-project-2026.firebasestorage.app',
    measurementId: 'G-PZ63K3G969',
  );

}